[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies]
promql = "0.4.2"
common = { path = "../common" }
snafu = "0.7.0"
criterion = "0.3.5"

[[bench]]
name = "promql"
harness = false
